package com.sriram.ecommerce.user.model;// default package
// Generated 26-Dec-2025, 6:12:07 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles"
        , uniqueConstraints = @UniqueConstraint(columnNames = "role_code")
)
public class Roles implements java.io.Serializable {


    private int roleId;
    private String roleCode;
    private String description;
    private List<Users> users;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "role_id", unique = true, nullable = false)
    public int getRoleId() {
        return this.roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }


    @Column(name = "role_code", unique = true, nullable = false, length = 150)
    public String getRoleCode() {
        return this.roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }


    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "roleses")
    public List<Users> getUsers() {
        return users;
    }
    public void setUsers(List<Users> users) {
        this.users = users;
    }
}


