package com.sriram.ecommerce.user.model;// default package
// Generated 26-Dec-2025, 6:12:07 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * UserStatus generated by hbm2java
 */
@Entity
@Table(name = "user_status"
        , uniqueConstraints = @UniqueConstraint(columnNames = "status_code")
)
public class UserStatus implements java.io.Serializable {


    private int userStatusId;
    private String statusCode;
    private String description;
    private List<Users> users;


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_status_id", unique = true, nullable = false)
    public int getUserStatusId() {
        return this.userStatusId;
    }

    public void setUserStatusId(int userStatusId) {
        this.userStatusId = userStatusId;
    }


    @Column(name = "status_code", unique = true, nullable = false, length = 150)
    public String getStatusCode() {
        return this.statusCode;
    }

    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }


    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userStatus")
    public List<Users> getUsers() {
        return users;
    }

    public void setUsers(List<Users> users) {
        this.users = users;
    }
}


